version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # stops overwriting of this folder in the docker container (deps should remain)
    environment:
      - CHOKIDAR_USEPOLLING=true  # uses fs.watchFile instead of fs.watch, as it is better in virtualized systems